### ISSUE TITLE
Paragraph diaporama taille images ?

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#101]
Diaporama : est-il possible d'ajuster proportionnellement à la largeur/hauteur de l'image (éviter de déformer l'image) ?
Pourquoi les images sont indiquées en 900*600 alors que je les traite en 750... j'ai l'impression que le rendu des images est ainsi détérioré... (voir exemple des images d'entête des pages)

**Comment by jabberwooki** [comment]
Ok, remplacer le style d'image 900x600 par 750x500.

**Comment by jabberwooki** [comment]
Corrigé. Le nouveau style d'image slide_750x500 est créé et remplace slide_900x600 dans l'affichage des bundles Diaporama.

**Comment by webmanagerPNF** [comment]
non c'était pas ca... j'ai fait toutes les images des pages en 900 il faut donc laisser 900 car sinon ca coupe l'image... mais elle doit se redimensionner proportionnellement en 750. On laisse 900 car normalement il doit y avoir la lightbox dessus pour zoomer l'image...

Désolée de cette confusion... mais j'ai fait et formé le PNC sur les images en 900...

**Comment by webmanagerPNF** [comment]
Je ré ouvre finalement cette issue car j'ai fait travailler toutes les images en 900*x donc serait il possible de conserver l'image natif de l'image en 900 de large mais qu'elle se recale bien en 750*x.
La hauteur du slider elle serait bien fixée à 500... si l'image est trop haute est elle est tronquée visuellement si elle est trop courte le fond de la page apparait... cette modification intervient car l'idée serait ensuite de pouvoir faire un zoom sur ce slider (comme c'est le cas sur les autres images dans les bundles (50/50 ou galerie)...

**Comment by jabberwooki** [comment]
L'image, quelle que soit sa taille initiale, est recadrée en 750x500.
Lors de la conf tél du mardi 16/02, Cécile indique de fermer ce ticket.
