### ISSUE TITLE
Paragraph BAckground color 1 2 3

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#102]
Texte couleur de fond : est il possible de donner une nom explicite aux couleurs à la place des numéros ? Gris, bleu, orange

**Comment by webmanagerPNF** [comment]
le changement de couleur ne fonctionne pas le fond est toujours BLEU

**Comment by jabberwooki** [comment]
Non, il n'est pas possible de nommer les couleurs puisqu'elles seront différentes d'un site à l'autre.
