### ISSUE TITLE
Ckeditor H3

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#103]
Style TITRE 3 : Peut être prévoir un padding en dessous mais pas au car cela fait un décalage lorsque l'on a une image à droite (voir sur la page Le Festival Nature)

**Comment by webmanagerPNF** [comment]
Finalement je suis obligée de ré-ouvrir cet issue car le padding au dessus du H3 manque finalement dans les pages classiques... Désolée...

**Comment by sographik** [comment]
Un exemple de page à me donner ?

**Comment by webmanagerPNF** [comment]
DES DECOUVERTES > Festival nature
