### ISSUE TITLE
Page avancée colonne de droite

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#104]
Comment sont gérés les éléments dans la colonne de droite prévus sur la maquette : 
http://pnx.espaces-naturels.fr/mutweb_pnc_html/page_complete.html

**Comment by jabberwooki** [comment]
Il est nécessaire de préciser le besoin pour cette colonne de droite.

Nos questions/remarques : 

- Les trois champs de la colonne de droite visibles sur la maquette ne peuvent pas être des bundles Paragraphs. En effet, si c'est le cas, ils ne sont pas connus à l'avance par Drupal et donc il est impossible de les positionner en colonne de droite via Display Suite. Ca doit donc être des champs classiques à créer dans le type de contenu Page avancée.

- Est-ce que la colonne de droite est prévue pour ne contenir que les 3 champs présentés dans la maquette : chiffres-clés, géolocalisation, articles liés ? S'il y en a d'autres, lesquels sont-ils ?

- Que doit contenir le champ Articles liés, vu qu'il n'y a pas de type de contenu Article ? S'agit-il des actus, des événements de l'agenda, d'autre chose encore ?

**Comment by webmanagerPNF** [comment]
Pour le moment nous n'avons pas eu de besoin pour gérer des informations types chiffres clés ou localisation sur le côté...

Privilégions prioritairement la jonction des articles "Actualités" uniquement. Si des articles ACTUALITES sont liée alors le colonne apparaît. Sinon la fenêtre ce recentre. 

Pour la liaison des articles il serait souhaitable de faire une sélection manuelle des articles et non une gestion par mots-clés trop aléatoire...

**Comment by jabberwooki** [comment]
Fonctionnement de la colonne de droite mis en place.
Nouveau champ Articles liés (field_page_linked_content) ajouté. Champ de type auto-complétion. Il suffit de commencer à saisir un mot et toutes les titres d'actu contenant ce mot sont proposés. Pour lier plusieurs actus, il suffit de refaire la même chose, en séparant chaque titre sélectionné du suivant par une virgule.
Si ce champ est renseigné, le contenu Paragraphs de la page se place dans les 2/3 gauche et le contenu du champ dans le 1/3 droit. Si le champ n'est pas renseigné, le contenu de la page se centre automatiquement.

**Comment by webmanagerPNF** [comment]
Merci d’implémenter
![capture_articles_lies](https://cloud.githubusercontent.com/assets/16044354/13606165/3c87dc56-e54b-11e5-9a4a-8ecfa0ddcc4f.png)
 le CSS pour coller à la maquette comme ci-dessous

**Comment by jabberwooki** [comment]
CSS mis en place.

**Comment by webmanagerPNF** [comment]
Le filet de séparation est trop foncé et doit être en gris très clair

**Comment by jabberwooki** [comment]
Bon code couleur #d1d1d1 récupéré dans l'image ci-dessus et appliqué dans la feuille de style.
