### ISSUE TITLE
"Médiathèque" > "Images" manque breadcrumb et renommer le menu et la page

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#114]
Manque breadcrumb
Renommer le menu "Images" par "Galeries d'images"
Renommer la page "Galeries photo" par "Galeries d'images"

**Comment by webmanagerPNF** [comment]
Supprimer filet gris sous le titre

**Comment by jabberwooki** [comment]
Lien de menu et titre de page renommés.
