### ISSUE TITLE
Marchés publics intitulés des boutons

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#127]
Revoir l'intitulé des boutons en front-office (et intitulé des champs en back-office) : 
Lire la suite --> renommer "Plus d'informations"
Consultation de l'avis --> Renommer "Avis de consultation (.pdf)"
Dossier de consultation --> Renommer "Accès au dossier de consultation (lien)"

Back-office : le champ de description du suite à l'ajout d'un document "Avis de consultation" n'est pas utile à supprimer.

**Comment by webmanagerPNF** [comment]
A estimer

**Comment by webmanagerPNF** [comment]
A réaliser car nous avons toujours les bouton en Anglais...

**Comment by jabberwooki** [comment]
Traduction effectuée.
C'est à faire sur chaque site à la mise en production.
Ce n'est pas packagé dans la feature Marchés publics.
