### ISSUE TITLE
Actualités, Dossiers Back-office

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#129]
L'image phare ne sert que pour le listing (format carré) car c'est compliqué de trouver une image qui fonctionne au format carré et au format paysage.

Supprimer le champ Description et remplacer par la fonction PARAGRAPH.

Cela permet de gérer le contenu des actualités plus ou moins complexes avec images paysage ou portrait.

Cela permet de gérer la mise en page les dossiers qui peuvent être longs.

**Comment by jabberwooki** [comment]
Attention ! On ne peut pas supprimer le champ Description puisque Actus, Dossiers et Brèves sont en fait un seul et même type de contenu.
