### ISSUE TITLE
Paragraph renommer les modèles

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#130]
Renommer les modèles :
Diaporama : Grand image/Diaporama
Documents utiles : Documents téléchargeables
Images 3 colonnes : Galerie d'images (3 colonnes)
Texte : Texte (vidéo, iframe)
Texte fond coloré : OK
Texte/Image (50/50) : OK
Image/Texte (50/50) : OK

**Comment by jabberwooki** [comment]
Les 3 premiers modèles ont été renommés.
Texte reste nommé Texte.
Les modèles Iframe et Vidéo sont conservés pour deux raisons : 
- l'emploi de Scald dans les contenus est généralisé, donc on garde de champ Vidéo de type atom_reference dans le modèle Vidéo,
- les modèles Vidéo et Iframe possèdent un champ Titre que ne possède pas le modèle Texte.
