### ISSUE TITLE
CK Editor : liens www et mail

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#135]
Si l'on saisie directement une URL ou une adresse e-mail dans le texte, le lien se place automatiquement cependant on ne peut pas modifier le lien dans le back-office (impossible d'accéder aux propriété du lien) pour y placer le cible "Nouvelle fenêtre" par exemple.

**Comment by sographik** [comment]
Lorsque l'on clique sur le symbole lien dans Ckeditor, une popup s'ouvre, on renseigne le lien puis dans l'onglet cible on choisit "Nouvelle fenêtre". peux-tu accéder à cela ? Voir screenshot joint
![cible](https://cloud.githubusercontent.com/assets/6141230/12455681/dab81d48-bf9c-11e5-999e-923dd19ed83e.png)
