### ISSUE TITLE
Ckeditor table

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#146]
Prévoir style automatique des bordures de tableau 1px #3a353c
Style pour l'entête : fond couleur #f4f4f4

**Comment by webmanagerPNF** [comment]
La spécification de marge interne des cellules ne fonctionne pas... Il faudrait plus de marge interne dans les tableaux voir page "La création du Parc"

**Comment by webmanagerPNF** [comment]
Finalement la bordure est trop noire changer la couleur si possible #a0a0a0
