### ISSUE TITLE
Offres d'emplois sous-menu / catégories ordre

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#153]
L'ordre des sous menus ne correspond pas à l'ordre renseigné dans les catégories

**Comment by jabberwooki** [comment]
Quel est l'ordre souhaité, celui de la taxo ou celui qui est visible dans le sous-menu ?

**Comment by jabberwooki** [comment]
Après vérification, l'ordre affiché : 
- Offres d'emploi
- Service civique
- Stages
est le même dans le sous-menu de la rubrique Offres d'emploi, dans l'écran d'admin du vocabulaire Types d'emploi et dans le menu déroulant du champ Type d'emploi du formulaire de création/modification d'un emploi.
Je ferme le ticket.
