### ISSUE TITLE
Paragraph supprimer les modèles

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#162]
Supprimer les modèles :
Iframe : la fonction est présente dans l'éditeur du bloc TEXTE et plus simple à gérer ainsi
Vidéo : trop complexe a gérer via SCALD. Nous le gérerons avec une IFRAME dans la zone de texte

**Comment by jabberwooki** [comment]
Au cours de la réunion du 12/01/16, la décision a été de généraliser l'usage de Scald dans tous les types de contenu.
