### ISSUE TITLE
Brèves : rendre cliquable

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/pnf#164]
clic sur l'intitulé de la brève donne accès au listing des brèves

**Comment by sographik** [comment]
Pour rester homogène d'un point de vue ergonomique, il faudrait rajouter un lien "Toutes les brèves" comme sur les blocs "A la une", "Dossiers" et "Agenda"

**Comment by webmanagerPNF** [comment]
Dans un premier temps d'urgence serait-il possible de mettre en place rapidement le clic sur l'intitulé de la brève donne accès au listing des brèves. Je pense que dans un second temps nous devrons faire un accès à un fiche détaillée de la brève. Je vous ferai une issue pour éclaircir ce point.

**Comment by jabberwooki** [comment]
Le clic lié à la liste des actus est en place.

Remarque concernant le clic vers la fiche en remplacement du clic vers la liste.
Actuellement la liste des brèves ne permet pas d'accéder à la fiche détaillée de chaque brève. C'est un choix de conception qu'on a fait ensemble. Et c'est logique, une brève étant une brève, il n'y a pas plus à voir sur la fiche détaillée d'une brève que sur la liste des brèves. Sinon, ce n'est plus une brève, ça devient une actualité. Donc, il est illogique de permettre d'accéder à la fiche détaillée d'une brève depuis le bloc de la page d'accueil alors qu'on ne peut pas le faire depuis la liste des brèves.
