### ISSUE TITLE
Ajout d'une vidéo via ATOME

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#177]
L'affichage dans la médiathèque VIDEO n'est pas correct.
La vidéo prend 100% de l'écran sous le menu de droite.
Et le responsive ne fonctionne pas.
Pourtant on ne spécifie pas la taille puisqu'il ne s'agit que du code/url de la vidéo.

**Comment by jabberwooki** [comment]
Corrigé avec l'installation du  module Fitvids.
