### ISSUE TITLE
ATOME (Scald)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#184]
J'ai modifié une image accueil_tengmalm_rdescamps.jpg via la gestion des ATOMES mais l'image ne c'est pas redimensionnée. J'ai été obligée de retirer l'image de mon contenu (Diapositive) pour y inclure le nouvel ATOME.
Normalement si l'on modifie un atome (via le module ATOME) il devrait se mettre à jour (nouvelle dimensions) automatiquement dans les pages concernées ?

**Comment by sographik** [comment]
A tester

**Comment by webmanagerPNF** [comment]
Ce problème c'est renouvelé et est très embêtant car il serait logique que la gestion centralisée des médias permette la propagation sur toutes les pages du média modifié... A creuser...

**Comment by jabberwooki** [comment]
Réponse à la question ci-dessus : ça dépend.

Explication.
Un champ de type texte (ex. champ body) dans lequel on a inséré un atome image ou bien un champ de type atome reference est bien mis à jour lorsqu'on met à jour l'atome image qu'il contient (par ex. lorsqu'on change le fichier image que cet atome contient).
Mais dans le cas du type de contenu Diapositive, on a affaire à un champ de type image, auquel on a ajouté, en plus d'aller chercher le fichier image sur le disque dur, la possibilité de récupérer ce fichier image aussi depuis la bibliothèque Scald. Sauf que dans ce cas, le champ image de la diapo ne pointe pas vers un atome image, mais vers le fichier image que contenait l'atome qu'on a sélectionné. Si ensuite, le fichier image de cet atome est modifié, le champ image de la diapo n'est pas au courant. Il faut en effet supprimer puis inclure à nouveau l'atome concerné.

Pour que la mise à jour de l'image soit répercutée automatiquement dans le champ image de la diapo, il aurait fallu mettre en place un champ de type atome reference (fourni par Scald) et non de type image (fourni par le noyau Drupal). Mais dans ce cas, il aurait été impossible de donner le choix d'uploader l'image soit depuis Scald soit depuis le disque dur.

**Comment by webmanagerPNF** [comment]
L'objectif de la bibliothèque étant bien une gestion centralisée il faudra faire évoluer ce point pour que même ce champ puisse prendre en compte des modifications d'atomes centralisée.
