### ISSUE TITLE
Form filtres listing actualités/agenda...

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#186]
Les champs de recherche du type catégories, secteur, public sont trop larges et ne tiennent plus sur une ligne.

**Comment by webmanagerPNF** [comment]
Traduire l'info "Leave blank for all. Otherwise, the first selected term will be the default instead of "Any"."

**Comment by jabberwooki** [comment]
Corrigé en cachant le <p class="help-block"> via css.
