### ISSUE TITLE
paragraph : texte/image 50/50 légende photo

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#187]
Ajouter la légende de l'image sous l'image en tout petit cf maquette + ajouter la légende dans la lightbox

**Comment by jabberwooki** [comment]
Corrigé.
(voir fonctions pnf_advanced_pages_entity_view_alter() et pnf_advanced_pages_entity_view() dans feature pnf_advanced_pages, ainsi que le code jquery dans pnf_advanced_pages.js(
