### ISSUE TITLE
ajout page/rubrique dans "Le parc national de..."

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#188]
J'ai créé une page et j'ai voulu FOURNIR UN LIEN DE MENU dans le menu "Le parc national de..." et la rubrique ne se positionne pas sous cette entrée mais au même niveau. Cela fait donc un bug sur le menu. Il faut alors allez changer l'ordre dans la fonction Structure > Menu

**Comment by sographik** [comment]
A tester

**Comment by webmanagerPNF** [comment]
OK ca marche
