### ISSUE TITLE
paragraph texte/image 50/50 taille de l'image

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#190]
L'image doit être redimensionnée de manière homothétique, s'il s'agit d'un format portrait il ne faut pas redimensionner l’image au format paysage. Voir rubrique "Le parc national de...">"Un territoire reconnu"

**Comment by webmanagerPNF** [comment]
Idem pour image/texte 50/50

**Comment by jabberwooki** [comment]
Création d'un style d'image "Largeur 360" (pas de hauteur définie). Ainsi, les images au format portrait ne sont plus tronquées.
