### ISSUE TITLE
espace entre les paragraph

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#191]
J'ai l'impression qu'il y a des espaces "padding ?" entre les paragraph ?? Est-il possible de les enlever ?? Voir sur la page "Le parc national> Un territoire reconnu"

**Comment by sographik** [comment]
Entre les balises <p></p> ou les bundles de paragraph ?

**Comment by webmanagerPNF** [comment]
entre les bundles de paragraph

**Comment by webmanagerPNF** [comment]
Capture espaces à uniformiser ![espace_bundle](https://cloud.githubusercontent.com/assets/16044354/12445989/c98f511a-bf67-11e5-9aeb-d24ca6f1d96f.jpg)

**Comment by sographik** [comment]
J'ai réduit de motitié l'espace margin-top:15px à la place de 30px.
