### ISSUE TITLE
paragraph > texte : styles de paragraphes

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#193]
J'ai toujours le style INTRO au lieu de CHAPEAU

**Comment by sographik** [comment]
Il faut vider les caches du site drupal pour voir la modification

**Comment by webmanagerPNF** [comment]
Je n'arrive pas à le voir j'ai fait Vider le cache des pages mais rien n'y fait...

**Comment by sographik** [comment]
![cache](https://cloud.githubusercontent.com/assets/6141230/12454830/74d1aaba-bf99-11e5-8062-b3e8d0825b8a.png)
