### ISSUE TITLE
SCALD insérer un fichier PDf dans un champ texte

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#195]
Lorsque j'insère un fichier PDF (glisser, déposer) via SCALD dans un bundle texte (page avancée)  ela ajoute le picto PDF par défaut dans des tailles vairables en fonction des tests. Est-il possible de ne pas avoir ce picto ?

**Comment by jabberwooki** [comment]
Corrigé.
INFO : Un clic droit sur le nom du fichier PDF qui a été glissé/déposé permet de modifier ou supprimer la légende ajoutée par Drupal sous ce nom de fichier.

[Info dev]
Effectué par surcharge du template de Scald File (scald-file-render.tpl.php).
