### ISSUE TITLE
Front-office Menu à droite des rubriques Actualité, Agenda, Marchés publics, Offres d'emploi, (RAA?)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#199]
Supprimer le titre au dessus du menu de droite.

Attention dans la MEDIATHEQUE il n'y a pas le titre au dessus du menu mais celui-ci est trop collé vers le haut il doit s'aligner verticalement sur le titre de la page à gauche

**Comment by jabberwooki** [comment]
Titres de menu supprimés dans les rubriques Actualités (et donc Agenda) et Marchés publics. Titre déjà non visible dans rubrique Emploi.
