### ISSUE TITLE
Images intégrées via SCALD dans bundle 

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#201]
Les images intégrées via SCALD dans un bundle texte (Voir page Les réseaux) sont intégrées avec l'url en dur (c'est à dire url du site de prod) est-ce que cela n'aura pas d'effets lors du passage sur le www ?

**Comment by webmanagerPNF** [comment]
Attention à ce point pour la mise en ligne de LUNDI

**Comment by jabberwooki** [comment]
J'ai eu ce jour (1er février 2016) confirmation par tél du support technique d'Ovea que les urls prod et preprod resteront en place tant que PNF ne demandera pas leur suppression. Donc les images utilisant ces liens resteront visibles.
