### ISSUE TITLE
CSS Agenda

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#204]
Bug CSS voir l'événement "Cévennes en lumière" si la date et le lieu sont un peu long cela provoque une décalage. A caler selon maquette http://pnx.espaces-naturels.fr/mutweb_pnc_html/agenda.html

**Comment by webmanagerPNF** [comment]
idem catégorie, idem public

idem le focal point ne fonctionne pas dans la page détail de l'événement

**Comment by sographik** [comment]
Des modifications css ont été réalisées pour faire mais la maquette ne prévoit pas quand il y a plusieurs lieux par exemple... Comme sur l'évènement "25° édition du Festival Contes et Rencontres"
