### ISSUE TITLE
Ckeditor : Bug alignement images (centrer)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#209]
Il est très compliqué de centrer les images dans l'éditeur...

De plus quand on rajoute des images dans CKEDITOR via SCALD voici le code source qui est rajouté.
![bug_code_source_ajout_img_scald](https://cloud.githubusercontent.com/assets/16044354/12482390/8bcadf46-c04f-11e5-9625-3661dc09d7da.jpg)
![bug_aligenements_ckeditor](https://cloud.githubusercontent.com/assets/16044354/12482391/8bced40c-c04f-11e5-8884-790d6ee09299.jpg)

A quoi cela sert-il ?

**Comment by sographik** [comment]
voir problème avec .img-responsive et son display:block

**Comment by sographik** [comment]
A tester sur la preprod !
