### ISSUE TITLE
sous IE (9.0.8112.16421) il y a un problème avec  le SLIDE.

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#215]
Voir peut etre si la compression des javascript est activé sur la prod

**Comment by jabberwooki** [comment]
La compression des fichiers javascript et css est activée sur la prod.
Sophie, est-ce que le problème sous IE persiste ? Je ne peux pas tester de mon côté, n'ayant pas IE.

**Comment by webmanagerPNF** [comment]
J'ai toujours le problème sous IE...

**Comment by webmanagerPNF** [comment]
Toujours le problème !! URGENT !!

**Comment by jabberwooki** [comment]
Correction apportée : 
- Librairie carousel.js fournie par Boostrap désactivée.
- Remplacée par la librairie carousel.js fournie par [barryvdh sur github](https://gist.github.com/barryvdh/6155151) pour corriger le pb IE9.

MAIS de toute façon, la méthode matchMedia de javascript utilisée dans le site ne fonctionne qu'à partir de IE10.. Donc inutile de vouloir faire fonctionner le site sous IE9.
