### ISSUE TITLE
Menu outils à droite --> Revoir l'ordre des pictos et ajouter pictos

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#217]
La mise à jour a désorganisé l'ordre des pictos :
- Actualités
- Agenda
- Journal du Parc
- Médiathèque
- Cartothèque URL _blank
- Boutique en ligne URL _blank : boutique.cevennes-parcnational.fr PICTO : http://fortawesome.github.io/Font-Awesome/icon/shopping-cart/
- Destination Parc national des Cévennes URL _blank : http://destination.cevennes-parcnational.fr/ PICTO : http://fortawesome.github.io/Font-Awesome/icon/map-signs/

**Comment by jabberwooki** [comment]
Les nouveaux liens ont été créés et l'ordre des liens a été rétabli.

Mais il faut tenir compte de la chose suivante. Deux liens appartiennent à la configuration du site et sont systématiquement exportés : Actualités et Médiathèque. Tous les autres liens sont propres à chaque site de Parc.

Actualités possède maintenant un poids de 0 et Médiathèque un poids de 10.
- Si l'on veut qu'un lien propre à un site apparaisse avant Actualités, il faut lui attribuer un poids inférieur à 0.
- Si l'on veut qu'il apparaisse entre Actualités et Médiathèque, il faut lui attribuer un poids de 1 à 9.
- Si l'on veut qu'il apparaisse après Médiathèque, il faut lui attribuer un poids supérieur à 10.
Pour cela, il ne faut pas ordonner les liens par glisser-déposer, mais cliquer sur le lien "Afficher le poids des lignes" situé en haut à droite de l'écran d'administration des liens d'un menu et attribuer les poids à la main. Si cette règle n'est pas respectée, chaque nouvelle mise à jour d'un site risque de modifier l'ordre des liens.
