### ISSUE TITLE
Mettre en place les outils : imprimer, partager, rss, A+,A- sur toutes les pages du site

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#218]
voir site de référence pour cela exemple sur http://www.reunion.fr/decouvrir/cote-mer

**Comment by webmanagerPNF** [comment]
Revoir le style ;)

**Comment by jabberwooki** [comment]
Le style fourni par les maquettes a été appliqué.

**Comment by webmanagerPNF** [comment]
Il manque les flux RSS sur :+1: Actualités, Agenda, Brèves, Offres d'emplois et de stages, Marchés publics

**Comment by jabberwooki** [comment]
Le flux RSS sera à reconsidérer plus tard.
