### ISSUE TITLE
Titre de bean "Contactez-nous"

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#22]
Créer un champ titre à cause du bug

**Comment by jabberwooki** [comment]
Champ Intitulé du texte (de type texte simple) créé.
De plus, un formateur de champ custom "HTML wrapper" est créé et mis à disposition des champs de type texte simple. Ce formatteur permet d'englober le champ avec la balise html de son choix (h2, h3, p...) et d'ajouter une (ou plusieurs) classe css à cette balise.
