### ISSUE TITLE
Page de base --> Styles

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#224]
Les styles par exemple "Intro" ne d'appliquent pas dans le champ BODY.
Voir exemple sur la page d'atterrissage DES CONNAISSANCES

**Comment by sographik** [comment]
@jabberwooki  il faut je pense voir la configuration de l'éditeur pour les page de base : même réglages sur le body que les autres types de contenu (full html ..etc)

**Comment by jabberwooki** [comment]
Non reproductible.
Le style Intro s'applique sur le body dans une page de test en prod. La page de test a ensuite été supprimée.
