### ISSUE TITLE
Focal point

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#226]
Dans page avancée > bundle galerie 3 colonne
J'ai essayé de recentrer la chauve-sourie mais ça ne marche pas vous savez pourquoi ?
Des connaissances>Les patrimoines>La faune>Les mammifères

**Comment by jabberwooki** [comment]
Corrigé en créant un nouveau style d'image focal_270x180.
Ce style est utilisé en remplacement du style 270x180 dans le bundle 3 images.
ATTENTION ! Il est nécessaire de revenir sur les images qui ont besoin d'être recentrées en sauvegardant à nouveau chaque page concernée.
