### ISSUE TITLE
Outil dans menu de droite >> Ajouter une entrée

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#227]
Titre : Base de données documentaire
Picto : http://fortawesome.github.io/Font-Awesome/icon/book/
URL en _blank : http://centre-documentation.cevennes-parcnational.net/

**Comment by webmanagerPNF** [comment]
Dernière position pour le moment

**Comment by jabberwooki** [comment]
Le lien Base de données documentaire est en place, avec le picto demandé.
