### ISSUE TITLE
Paraghaph : problème avec les ancres

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#228]
Après avoir inséré des ancres dans différents bundle d'une même page.
Je ne retrouve pas l'ensemble de mes ancres si je me place dans le premier bundle pour faire mes liens internes...
En dépannage, j'ai bidouillé pour que cela fonctionne en faisant les liens à la main dans le code source, cela fonctionne sous FF mais pas sous Chrome ? Est-ce que cela fonctionne chez vous sous Chrome ?
Exemple sur le DOSSIER : La laine : un nouvel avenir en Cévennes ?

**Comment by jabberwooki** [comment]
Problème assez complexe.
1) Un champ CKEditor ne peut pas connaitre les ancres créées dans un autre champ CKEditor. Donc il faut bien faire les liens à la main.
 2) Une fois créés, ces liens internes à une même page fonctionnent bien sous FF mais pas du tout sous Chrome.

Donc j'ai fait un code custom en jquery pour transformer ces liens en <span> mais avec le même look et qui réagissent au clic de la souris en déplaçant la fenetre du navigateur jusqu'à l'ancre cible.
IMPORTANT : il faut atribuer à chaque lien la classe "pn-anchor" pour que le code jquery fasse sa transformation.

Ces pseudo-liens fonctionnent très bien sous les deux navigateurs.
