### ISSUE TITLE
bundle IFRAME et VIDEO

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#231]
Doit être un Champ EDITEUR TEXTE BRUT sans éditeur dans lequel on copie-colle les propriétés HTML de l'IFRAME exemple : pour une vidéo externe au parc 

<iframe width="640" height="360" src="https://www.youtube.com/embed/NTqGNy6Ya9A" frameborder="0" allowfullscreen></iframe>

**Comment by jabberwooki** [comment]
C'est en place. Quelques explications.

Lorsqu'on crée un nouveau paragraphe de type Iframe, on arrive maintenant sur l'éditeur au format texte brut. Il suffit d'y coller le code de l'iframe récupéré sur un site externe.

Par exemple, pour la vidéo Youtube [Rendez-vous à Mas Camargue](https://www.youtube.com/watch?v=HpAzDaQFCIs), il faut coller le code suivant : 
`<iframe width="560" height="315" src="https://www.youtube.com/embed/HpAzDaQFCIs" frameborder="0" allowfullscreen></iframe>`

Mais ATTENTION ! Il faut sauvegarder au format Full HTML pour enregistrer correctement ce code et pour que la vidéo apparaisse dans la page, comme indiqué dans la capture d'écran ci-dessous.

![iframe-texte-brut](https://cloud.githubusercontent.com/assets/1741337/12713480/414d3d28-c8cf-11e5-8fad-15ff693612af.png)
