### ISSUE TITLE
"Médiathèque" > "Publications et documents" vignettes des documents trop petites cf maquette

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#232]

**Comment by jabberwooki** [comment]
La maquette n'est pas calée sur une grille Bootstrap 12 colonnes.
Actuellement l'affichage est réglé sur 2-10 (image dans la région gauche de 2 colonnes de large, texte dans la région droite de 10 colonnes de large).

Si l'on modifie ce réglage pour le passer à la prochaine valeur la plus proche, soit 3-9, la région gauche occupera alors 25 % de l'espace et la région droite 75%. L'image dans ce cas sera alors de 187 px de large, ce qui est environ 40% plus large que sur la maquette.

Cécile, est-ce que tu confirmes ce nouveau réglage 3-9 ?

**Comment by webmanagerPNF** [comment]
Je comprends et je ne souhaite pas que l'on passe sur le 3-9 cependant je constate que les images PAYSAGES font 100px de large alors que les images PORTRAIT font 71 n'est-il pas possible de passer les formats PAYSAGES aussi à 100px de large ?

**Comment by jabberwooki** [comment]
Corrigé. Nouveau style d'image appliqué. Les images sont réduites à 160 px de large, la hauteur s'adapte proportionnellement. Elles s'affichent en fait à 111 de large dans la liste des documents et à 160  de large dans la page Journal du parc (qui n'a pas de menu en colonne de droite).
