### ISSUE TITLE
moteur de recherche ne fonctionne pas

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#235]

**Comment by jabberwooki** [comment]
C'était normal, nous n'avions encore fait aucune indexation des contenus. Je viens de la lancer à la main. Les 137 contenus déjà saisis (actus, agendan, documents, ...) sont maintenant trouvés par le moteur de recherche.
J'envoie en parallèle un mail a Ovea pour qu'ils mettent en place le mécanisme automatique d'indexation. Eux seuls peuvent le faire vu que nous n'avons pas d'accès admin sur le serveur aten-13.
