### ISSUE TITLE
améliorer dès que possible le responsive du site

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#236]
-  surtout le header
- prévoir un gros bouton de navigation qui reprendra le menu thématique et le menu parc
- prévoir un gros bouton "outils" qui reprendra les outils du menu de droite
- prévoir un gros bouton pour le moteur de recherche
- prévoir un gros bouton pour le changement de langue
- le reste ne s'affiche plus dans le header

Voir RESPONSIVE http://www.ecrins-parcnational.fr/

HOME : supprimer le slider, aligner les blocs/images et les espacer correctement

FOOTER
Enlever la carte de france / voir l'espace entre les différents éléments

**Comment by sographik** [comment]
Reste à peaufiner quelques affichages mais l'essentiel de cet issue a été réalisé. 
Pour rappel : une tâche = une issue
