### ISSUE TITLE
Réseaux sociaux MENU HAUT ET FOOTER (très urgent !)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#238]
FB : https://www.facebook.com/Parc.national.des.Cevennes
Twitter :https://twitter.com/PnCevennes
Youtube : https://www.youtube.com/channel/UCnfhAcy-fgEj7TCP4qxzN6g

**Comment by jabberwooki** [comment]
Corrigé.
La saisie des urls de chaque réseau social se fait sur la page suivante : 
http://prod-pnc.parcnational.fr/fr/admin/config/services/on_the_web
