### ISSUE TITLE
Largeur des pages : problème sur les actualités (à corriger)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#240]
Sur la dernière actu "Le nouveau site" l'image de la page d'accueil du site affiche un fond noir.
merci de mettre au pire un fond blanc dans un premier temps puis voir pour régler la largeur dans un deuxième temps. merci !

**Comment by sographik** [comment]
Il y a un fond noir car l'image chargée est probablement moins large que la largeur maximale possible (395px). Si je mets un fond blanc au survol de l'image le fond sera blanc avec une opacité réduite...

**Comment by jabberwooki** [comment]
Corrigé. Le style d'image utilisé pour ce bundle (texte-image 50/50) n'était en effet pas assez large. Je l'ai passé de 360 à 400px de large. Le champ étant responsible, la largeur de l'image s'adapte maintenant parfaitement à l'espace disponible.
Même correction faite sur le bundle image-texte 50/50.
