### ISSUE TITLE
footer : rendre la carte cliquable avec lien  (pour accéder à la carte du territoire)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#244]

**Comment by jabberwooki** [comment]
Ou se trouve cette carte du territoire ?

**Comment by webmanagerPNF** [comment]
http://maps.cevennes-parcnational.net/#/maps/limites_pnc

**Comment by webmanagerPNF** [comment]
En _blank STP. Merci.

**Comment by jabberwooki** [comment]
Fait à l'aide d'un champ supp. pour saisir l'url et du module linked_field.

**Comment by webmanagerPNF** [comment]
Je ne visualise pas cette modification ? Est-ce normal ?

**Comment by jabberwooki** [comment]
Oui, il manquait juste l'url. Je l'ai ajouté, la carte est maintenant cliquable.

Au cas ou, pour changer ce lien, dans le menu admin il faut passer par : 
Contenu > Blocs 
puis cliquer sur le lien Modifier de "bloc contact accueil"
et changer la valeur du champ "Lien vers carte du territoire".
