### ISSUE TITLE
Marché public : Traduction CONTRACT NOTICE 

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#245]
A traduire : Avis de consultation (.pdf)

**Comment by jabberwooki** [comment]
Traduction saisie.

**Comment by webmanagerPNF** [comment]
Est-il possible de rajouter  (.pdf) à la fin : "Avis de consultation (.pdf)". Merci.

**Comment by jabberwooki** [comment]
C'est rajouté.

Pour info, c'est de la traduction et ça se passe là : 
http://www.cevennes-parcnational.fr/fr/admin/config/regional/translate/translate
Il suffit de mettre "Contract notice" dans le filtre de recherche et Drupal retourne la liste des chaines de caractère contenant ces mots. Ensuite un clic sur Modifier de la ligne concernée et on peut ajuster la traduction.
