### ISSUE TITLE
Réécriture d'URL

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#247]
Je ne comprends pas, la réécriture des URL place un numéro à la fin des URL et le titre de la page n'est pas intégré à l'url... comment corriger correctement cela ? Puis je le faire sans passer à la main sur chaque page ?
/fr/des-connaissances/les-patrimoines/les-milieux-naturels-5 > Alors que je suis dans l'arborecence sur 
Des connaissances/Les patrimoines/Les milieux naturels/Les forêts

**Comment by jabberwooki** [comment]
Corrigé. C'était une erreur de motif pathauto pour les pages avancées (node:menu-link:parents:join-path] alors qu'il fallait [node:menu-link:parents:join-path]**/[node:title]**)

J'ai du reprendre quelques pages à la main, pour lesquelles l'option " Générer automatiquement l'alias d'URL" avait été décoché.
