### ISSUE TITLE
Menu picto outils

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#257]
Remonter en haut de slideshow

**Comment by sographik** [comment]
A peu près un peu en dessous des pictos imprimer A+ A- ...etc

**Comment by webmanagerPNF** [comment]
Ca fonctionne pas sur les petits écrans... URGENT.

**Comment by sographik** [comment]
Petits écrans ? Tu veux dire smartphones ou écrans d'ordinateur 13 pouces ?

**Comment by webmanagerPNF** [comment]
C'est sur des écrans d'ordinateurs portables testé sur une hauteur de 768px. Voir capture ci-dessous
![capture_pnc_pour_cecile](https://cloud.githubusercontent.com/assets/16044354/13605434/e020cd9a-e547-11e5-9310-5023de7ce224.jpg)
