### ISSUE TITLE
PNC : Le style CHAPEAU n'est plus en ORANGE mais en gris 

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#263]

**Comment by sographik** [comment]
Sur PNF ?

**Comment by webmanagerPNF** [comment]
PNC

**Comment by jabberwooki** [comment]
Corrigé.

[Info dev]
Le paramétrage **_$conf['park_code'] = 'pnc';_** avait disparu du fichier settings.php.
Pourquoi ? Mystère.
