### ISSUE TITLE
PNV - Problème affichage aide au passage souris (cf. capture)

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#265]
Agenda, filtre sur les catégories,  secteurs, publics...

![bug_affichage_pnv](https://cloud.githubusercontent.com/assets/16044354/14382085/833e4312-fd8b-11e5-9d5a-7743bfe75d8c.jpg)

**Comment by jabberwooki** [comment]
L'affichage de cette aide est généré par le plugin Tooltip de Bootstrap.
Le présent bug a disparu lors de la désactivation de ce plugin Tooltip pour une autre raison (affichage déployé des menus du haut de page et déstructuration de l'affichage du menu latéral).
