### ISSUE TITLE
SCALD : Insertion d'une image dans un paragraph TEXTE

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#267]
Lorsque l'on fait glisser un ATOME image dans un paragraph de texte. On ne dispose plus des propriétés de l'image (comme avant) mais désormais des propriétés de l'ATOME. Ce qui ne permet plus  : 
- de modifier la taille de l'image si l'on souhaite la réduire un peu
- de placer un lien (cible New window) sur l'image
  ![porpriete_atom](https://cloud.githubusercontent.com/assets/16044354/14534382/3acf831a-0269-11e6-8542-38b869167931.jpg)

**Comment by jabberwooki** [comment]
Il ne s'agit pas d'un bug. Ce changement est dû à l'activation du plugin **Scald Drag'n'drop integration** dans les paramétrages de CKEditor.

Comparaison des 2 réglages : 

1 - avec activation du plugin
Un clic droit sur l'image donne accès à un menu contextuel permettant de gérer l'atome.
Si l'on veut redimensionner les images glissées/déposées, il faut alors décider des formats (contextes scald) à mettre à disposition de l'utilisateur.

2 - sans activation du plugin
Le clic droit donne accès au menu ckeditor classique de paramétrage d'une image. L'utilisateur peut donc choisir lui-même hauteur et largeur de l'image.

Si l'image initiale, telle qu'elle est stockée dans Scald, fait par exemple 2000x1000 pixels et que l'utilisateur à l'habitude d'insérer dans son texte des images de 100x50 pixels : 
- dans le premier cas, il change de contexte scald (à condition d'avoir créé ce contexte 100x50) et l'image envoyée au navigateur sera bien une image de 100x50.
- dans le second cas, il redimensionne l'image en lui donnant 100 px de large et 50 px de haut, mais l'image envoyée au navigateur sera l'image originale de 2000x1000, soit une image 20 fois pour lourde que nécessaire. S'il s'amuse à faire ça pour une dizaine d'image, on se retrouvera avec une page contenant 20Mo d'images.

Autre inconvénient de la solution 2 : si l'utilisateur saisit  par exemple 100x100 au lieu de 100x50 (ou toutes autres valeurs non proportionnelles au format de l'image d'origine), alors l'image sera complètement distordue (étirée en hauteur).

Il faut décider des formats d'image que les utilisateurs sont susceptibles d'utiliser et créer les contextes Scald correspondants.

**Comment by webmanagerPNF** [comment]
Si c'est automatisé, dans ce cas proposer 3 contextes prédéfnis :
150L * X haut
350L * X haut
600L * X haut

Est-il envisageable de proposer un zoom automatique sur ces images qui ouvrirait le format initial de SCALD ?

**Comment by webmanagerPNF** [comment]
A programmer rapidement.

**Comment by jabberwooki** [comment]
J'ai créé les trois contextes demandés.
J'ai aussi testé l'ouverture du format initial de l'image dans une colorbox. Sans succès.

[DEV] Il y a deux possibilités mais elles sont buggées toutes les deux :
- ajouter la class "colorbox-load" à l'image insérée => Bug javascript "TypeError: url is not defined"
- ajouter le module image_resize_filter et le configurer pour colorbox => aucun effet sur l'image insérée. La page du module indique même que ça ne marche pas dans Chrome et Safari pour des raisons d'implémentation de ces navigateurs.
