### ISSUE TITLE
URGENT TOUS PNX : Largeur pages actualités

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#268]
Depuis que nous avons installé PARAGRAPH dans les actus la largeur des actus est trop grande par rapport à une page avancée il faut donc réduire la largeur des actu comme pour les pages avancées.

**Comment by jabberwooki** [comment]
Corrigé.

[Dev] Effectué à l'aide d'instruction jquery. Teste si la colonne de droite possède du contenu ou pas. Si non, elle est retirée du DOM et le titre + la colonne de gauche sont repositionnés au centre.
Voir fichier repository/modules/features/pnf_news/js/pnf_news.js

**Comment by webmanagerPNF** [comment]
Bug d'affichage de la galerie d'images : exemple sur l'actu du 10/05 en preprod du PNV

**Comment by jabberwooki** [comment]
Corrigé.
Les paragraph bundle 3 images s'affichent maintenant correctement

[Dev] Bug sournois, difficile à trouver.

Le bon code était déjà présent (ajout de la classe bootstrap col-md-4 aux 3 field-item du champ images_group) dans le fichier .../pnf_advanced_pages/js/pnf_advanced_pages.js, dans un bloc de code 
**Drupal.behaviours.advanced_pages**.

Mais lorsqu'on visite une page actu, un second fichier .../pnf_news/js/pnf_news.js est chargé aussi, avec son bloc de code jquery pour le bon centrage des pages en fonction du contenu de la colonne de droite. Sauf que, ce code était dans un bloc lui aussi nommé **Drupal.behaviors.advanced_pages**.

En renommant proprement ce second bloc Drupal.behaviours.news_page, il n'y a plus écrasement du second code par le premier et le bug disparait.
 Chaud, chaud, chaud ! 1h30 pour le trouver.
