### ISSUE TITLE
Page de base --> Styles

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#269]
Appliquer le fond blanc comme sur les autres pages
Exemple : https://www.cevennes-parcnational.fr/fr/les-parcs-nationaux-en-france

Back-office : mettre à disposition la bibliothèque d'Atomes car on ne peut pas insérer d'images sans cela.

**Comment by jabberwooki** [comment]
Corrigé.

[Dev]
Le fond des pages de base est bien paramétré pour être blanc (cf http://www.cevennes-parcnational.fr/fr/content/mentions-legales).
La page "Les parcs nationaux de France" est un cas particulier. C'est une vue qui affiche un node particulier (exporté via la feature kcore). Donc il s'agissait de passer en blanc le fond de la vue qui affiche cette page. Fait avec le sélecteur _**.view-exportables-pages .views-row**_ dans le fichier content.less
