### ISSUE TITLE
Erreur JS pour fermer les messages Drupal

### ISSUE THREAD

**Issue by zakxxi** [jabberwooki/pnf#27]
![image](https://cloud.githubusercontent.com/assets/1446617/10094850/23315fba-6365-11e5-9f98-d9425757313f.png)
![image](https://cloud.githubusercontent.com/assets/1446617/10094853/30416d80-6365-11e5-91f6-92a246c05eea.png)

**Comment by jabberwooki** [comment]
Non reproductible.
