### ISSUE TITLE
MAC : FF 38.0.5 ou Safari - BUG CKeditor

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#272]
L'éditeur CKeditor n’apparaît pas dans les champs de saisie.

**Comment by jabberwooki** [comment]
Tests effectués sur preprod-pnc avec :
- un MacBook Air, avec Safari 9.1.1 (10601.6.17)
- un emulateur Mac en ligne (www.browserstack.com) avec Chrome 38.0.2125.101

Dans les deux cas, CKEditor apparaît correctement.
