### ISSUE TITLE
Actualités : champs résumé et description

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#273]
Si c'est deux champs sont saisis cela génère une erreur d'affichage dans le listing les deux textes se superposent sur le over.

**Comment by jabberwooki** [comment]
Il y a effectivement un bug d'affichage, mais le symptôme est le suivant. Que l'on ai saisi un résumé ou pas, s'il le texte à afficher contient un passage à la ligne (ce que signifie que ckeditor crée deux paragraphes <p></p>), alors les deux paragraphes sont superposés.
Corrigé avec un bout de code jQuery.

[Dev]
C'est dû à un positionnement css. Les <p> sont passés en postion: absolute, top: 0px, donc l'un au dessus de l'autre. Ca aurait pû être corrigé en modifiant le css, mais il y a aussi un traitement jquery pour donner au <p> exactement la mm taille que l'image (codé par Adrien).
Donc la solution jquery a été de récuperer le texte de chaque <p> (il peut y en avoir plus de 2) et de tout réinjecter dans une seule balise <p>.
