### ISSUE TITLE
All : Ordre d'affichage des événements en page d'accueil

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#282]
L’ordre doit être inversé.

![agenda_accueil_pnv](https://cloud.githubusercontent.com/assets/16044354/17327961/40adb93e-58bb-11e6-8cea-dd9c67da5141.jpg)

**Comment by jabberwooki** [comment]
Corrigé, pour tous les sites.
Déployé en preproduction.
