### ISSUE TITLE
All : La fonction EPINGLER EN HAUT DE LISTE ne fonctionne pas sur les listings, actus, marchés, agenda...

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#285]

**Comment by jabberwooki** [comment]
Il était normal que ça ne fonctionne pas. Il s'agissait de rajouter le critère de tri "Epinglé" dans les vues concernées (ce qui n'était pas dans la demande initiale).
J'ai rajouté ce critères et déployé la modif en preproduction.
