### ISSUE TITLE
PAG (preprod) : Marches publics

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#289]
Le styles dans le champ Description ne s'affichent pas correctement
Le bouton "Contract link" n'est pas traduit (voir aussi pour l'autre bouton)
Le bouton "Lire la suite" est mal placé

**Comment by jabberwooki** [comment]
En vérifiant sur d'autres sites PNx, je me rends compte que "Contract link" n'a jamais été traduit.
Quelle traduction donner ? Dossier de consultation ?

**Comment by webmanagerPNF** [comment]
Oui idéalement "Dossier de consultation (lien)"

**Comment by jabberwooki** [comment]
Le style du champ Description ne s'afffiche pas encore correctement. Normal, il faut encore appliquer les codes couleurs spécifiques à PAG. Ce sera fait dans la journée.

Le bouton "Contract link" est traduit.

Le bouton "Lire la suite" est repositionné via une instruction css complémentaire
