### ISSUE TITLE
PAG (preprod) : Offres d'emploi

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#292]
Le styles dans le champ Description ne s'affichent pas correctement
Le bouton "Job notice" n'est pas traduit 
Le bouton "Lire la suite" est mal placé

**Comment by jabberwooki** [comment]
Idem Marché Publics, il reste à mettre les codes couleur dans les fichiers ckeditor pour que le champ Description s'affiche correctement. Ca arrive très bientôt.

Le bouton "Job notice" est traduite.

Le bouton "Lire la suite" est maintenant bien placé suite au correctif css effectué pour le ticket #289.
