### ISSUE TITLE
PAG (preprod) : Activation rubrique "Documents" dans menu footer

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#294]
J'ai activé les documents dans la médiathèque en footer mais l'ordre indiqué n'est pas respecté

**Comment by jabberwooki** [comment]
L'ordre est correct maintenant. Il l'était d'ailleurs dans le code HTML.
Mais il manquait les classes bootstrap (col-xs-6 col-sm-3 col-md-3) qui vont bien pour positionner correctement les liens les uns après les autres.
C'est dû au fait que, suite aux changements récents dans le menu footer, le lien Documents n'est plus embarqué dans aucune feature, donc les classes dont il a besoin non plus.

A rajouter à la main sur tous les sites ou l'on active ce lien Documents.
