### ISSUE TITLE
Upload des images 

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#296]
Voir pourquoi la qualité des images est dégradée lors de l'import dans les bundles (cf mail du 03/02/17)

**Comment by webmanagerPNF** [comment]
Idem vignette des dossiers à voir sur PNP image originale qualité HD et résultat flou

**Comment by jabberwooki** [comment]
Ceci n'est pas un bug. Le problème vient du fait que le format d'image utilisé dans un node événement de l'agenda est focal_820x410, donc 820px de large.

Les images citées en exemple dans le mail du 03/02/17 sont : 
[http://www.pyrenees-parcnational.fr/fr/agenda/les-gardes-du-gypaete](http://www.pyrenees-parcnational.fr/fr/agenda/les-gardes-du-gypaete)
[http://www.pyrenees-parcnational.fr/fr/agenda/le-pastoralisme](http://www.pyrenees-parcnational.fr/fr/agenda/le-pastoralisme)

Dans les 2 cas, les images d'origine uploadées lors de la créaton du node ont une largeur nettement inférieure à celle du format d'image focal_820x410 (617px et 547px respectivement). D'ou la distorstion observée et la dégradation de la qualité d'image.

Le webmaster du PNP a pu uploader de telles images parce qu'il n'y a pas de limite inférieure de taille dans le paramétrage du champ Image phare. Il est possible de placer une limite, mais dans ce cas le rédacteur sera dans l'impossibilité d'uploader son image, donc de créer son contenu. L'alternative est simple : 
- soit on place une limite et le webmaster sera dans l'obligation de trouver des images de résolution suupérieure à la limite paramétrée ou bien il ne pourra pas créer son contenu,
- soit on ne place pas de limite et dans ce cas le webmaster pourra toujours créer son contenu, mais aura de la dégradation de qualité chaque fois qu'il chargera une image de résolution inférieure à 820x410px.
