### ISSUE TITLE
PNP : Agenda - accueil et listing

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#299]
Les événements de l'agenda sur la page d'accueil ne se retrouvent pas dans le listing des événements dans l'agenda. Voir si l'issue #297 est bien réglée.

**Comment by webmanagerPNF** [comment]
Lorsque la date est dépassée ils restent affichés sur l'accueil. Solution : appliquer sur le bloc accueil les même filtres de dates que sur la page.

**Comment by jabberwooki** [comment]
Corrigé.
Le filtre de date manquant (date de fin >= maintenant) est ajouté au bloc Agenda de l'accueil.
