### ISSUE TITLE
Menu Footer médiathèque & Menu tools

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#3]
Il faut mettre des class sur chaques liens de menus afin de pouvoir leur attribuer un picto.
Je ne sais pas quelle est la meilleure solution à employer : Menu attributes ou Menu icon ou autre.

**Comment by zakxxi** [comment]
menu_attributes n'est pas activé par défaut, je le rajoute à kcore.

**Comment by zakxxi** [comment]
ajout des classes :

tool-news
tool-events
tool-media
tool-newspaper
