### ISSUE TITLE
Offres emploi formulaire de saisie

### ISSUE THREAD

**Issue by webmanagerPNF** [jabberwooki/pnf#300]
Champ PUBLIE LE 
Supprimer le champ HEURE (non nécessaire) car il génère un bug de saisie

**Comment by webmanagerPNF** [comment]
Modification réglage sur champ date "publié le"
Supprimer la granularité heure 
Format jj/mm/aaaa

**Comment by jabberwooki** [comment]
Champ Publié le modifié comme demandé.
Son format est maintenant d/m/Y.
