### ISSUE TITLE
Menu Tools - icons class à créer

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#31]
Actualités / Agenda / Journal du Parc / Médiathèque / Boutique / Soutenez le parc / Destination Cévennes.
Il faut mettre une class pour que je puisse mettre les pictos en place

**Comment by jabberwooki** [comment]
Seuls les liens Actualités et Médiathèque seront présent sur tous les sites (cf. maquette accueil_cequichange_entre_pnx.jpg) et sont embarqués dans des features (pnf_news et pnf_multimedia).
Le lien Actualité possédait déjà sa classe tool-news.
J'ai ajouté la classe tool-multimedia au lien Médiathèque.
Tous les autres sont à créer avec le nom de classe qui va bien dans chacun des sites, en fonction des besoins. Ces noms de classe doivent être listés dans la future doc d'install des autres sites.
