### ISSUE TITLE
Agenda liste - supprimer colonnes bootstrap dans les accroches

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#33]
cf : le bloc agenda de l'accueil pour mieux comprendre

**Comment by jabberwooki** [comment]
Colonnes supprimées en changeant la mise en page de **Bootstrap Two Columns: 6-6 stacked** à **Bootstrap One Column: 12**.

**Comment by sographik** [comment]
Le champ location doit être au dessus du champ dates.
D'ailleurs les champs catégorie/titre/location doivent être regroupés pour former un groupe group-event-resume  comme sur le bloc agenda de l'accueil.

**Comment by jabberwooki** [comment]
J'ai  créé le div group-event-resume.
Mais celui-ci ne contient que les champs Titre et Lieu puisque le champ Catégorie doit apparaître dans le coin supérieur gauche de l'image.
