### ISSUE TITLE
Document liste

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#40]
Selon la maquette "Documents" fournie par Cécile, il faudrait je pense faire des field group pour avoir un bouton "télécharger" avec nom du fichier et poids / un bouton "voir" icone de l'oeil / un bouton feuilleter icone de livre pour chaque doc.

**Comment by sographik** [comment]
Pas de champ date de publication apparent sur la liste d'après la maquette

**Comment by sographik** [comment]
La catégorie doit être au dessus du titre et non dans la colonne de la photo.

**Comment by sographik** [comment]
Le titre du document doit être un h3

**Comment by jabberwooki** [comment]
Terminé. Description du travail effectué.

__Gestion des fichiers PDF attachés__
Les deux champs initialement créés par Adrien (field_document_download et field_document_preview), qui nécessitait d'uploader 2 foix le même fichier sont supprimés et remplacés par un champ unique de type field_collection (field_document_links).
Ce champ field_collection contient 2 nouveaux champs : 
- field_document_download
- field_document_flip

Le premier contient le fichier uploadé, le second contient l'url Issuu ou Calaméo.

__Gestion des dates__
Comme pour Actualité, le champ Date de publication affichée est rajoutée et c'est celui-ci qui est affiché dans le teaser. L'autre champ Date (debut/fin de publication) est retiré de l'affichage.
 
__Affichage du teaser__
D'un point de vue de l'affichage, 3 choses sont mises en place : 
1 - Dans Display Suite, un champ dynamique local_flipthrough est créé. Il reprend le champ field_document_download, mais au lieu d'utiliser le formatter 'Direct Download File accessible', il utiliser 'PDF Reader'.
2 - Avant affichage, si le lien de feuilletage distant (Issuu, Calaméo...) est renseigné, alors le lien du viewer PDF est retiré de l'affichage.  Implémenté dans pnf_document_entity_view_alter(), 
3 - Pour les utilisateurs autorisés, un lien Modifier est affiché pour chaque document listé. Implémenté dans pnf_document_node_view().

**Comment by camillemonchicourt** [comment]
:+1:
