### ISSUE TITLE
Offres d'emploi listing

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#41]
Regarder la maquette sur Trello, les offres n'ont pas besoin 2 colonnes à priori finalement.
Le filtre type d'offre est en fait un menu sur la droite.

**Comment by jabberwooki** [comment]
- Les deux colonnes sont remplacées par un Bootstrap One Column 12.
- Vue initiale séparée en 3 vues : offres d'emploi, stages, services civiques.
- Suppression du filtre exposé et création du menu emplois, positionné via Context dans la sidebar second.
