### ISSUE TITLE
Offres d'emploi bouton class btn-secondary

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#45]
Pour les boutons "Fiche de poste" changer la class btn-primary par btn-secondary

**Comment by jabberwooki** [comment]
ATTENTION ! Classe changée mais le bouton btn-secondary apparait comme ceci : 

![listing-offres-emploi](https://cloud.githubusercontent.com/assets/1741337/10613359/22b3922a-7755-11e5-99b5-d81f5d9ebac5.png)
 En vérifiant si le code css correspondant était bien présent, j'ai vu sur github que tu avais modifié le fichier repository/themes/custom/pnf/bootstrap/less/buttons.less
Ce fichier est un fichier de la librairie bootstrap, pas un fichier de notre theme pnf custom. Si on met à jour la librairie, tout sera écrasé.
Les fichiers less custom sont dans repository/themes/custom/pnf/less et tout nouveau fichier custom créé doit être importé via la commande @import 'mon-fichier.less' dans le fichier styles.css.less
Demande confirmation à Adrien qui connait maintenant Boostrap bien mieux que moi.
