### ISSUE TITLE
Node Vidéo et Galerie : Droits et width

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#51]
une vidéo / une galerie doivent prendre toute la largeur du content à l'affichage dans leur node
+ afficher catégorie et résumé

**Comment by jabberwooki** [comment]
Autre point à traiter : Les vidéos ne sont pas visibles pour les anonymes.

**Comment by jabberwooki** [comment]
Les nodes vidéo sont maintenant sur  toute la largeur du contenu (via module Fitvids) et les galeries s'affichent maintenant avec le theme folio acheté sur galeria.io.
