### ISSUE TITLE
Page standard et page d'atterrisage

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#52]
class bootstrap à prévoir, pour le content : col-lg-offset-2 col-lg-8  et 3 images par ligne pour les pages d'atterissage.

**Comment by jabberwooki** [comment]
Rajout du fichier de template node--page.tpl.php au thème pnf. A ce fichier sont rajoutées les classes demandées.
Pour le nombre d'images par ligne dans les pages d'atterrissage, c'est un réglage propre à chaque site. Ce paramètre n'est pas embarqué dans une feature. Il se trouve sur la page d'admin suivante : 
Configuration > Interface utilisateur > Child menu items. On y règle le nombre d'images par ligne et le style d'image utilisé.
