### ISSUE TITLE
Menu footer / titre de bloc

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#6]
Pour ce Menu il faut afficher comme titre de bloc "Venir dans le Parc national" comme sur la maquette graphique.

**Comment by sographik** [comment]
a faire en co-working

**Comment by jabberwooki** [comment]
C'est réglé. C'était juste une confusion entre les menus "Venir dans le parc" et "Footer".
Après correction avec Sophie, le titre du menu "Venir dans le Parc national" s'affiche bien.
