### ISSUE TITLE
Menu déroulant du header à refaire !

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#62]
- Démonter les jump menus et les remplacer par du menu déroulant classique :
menu du parc : aucun lien exporté
menu les parcs nationaux : exporté

**Comment by jabberwooki** [comment]
**1 - Modifications effectuées pour les deux menus**
Suppression du code qui les transformait en jump menus dans la fonction kcore_block_view_alter() du fichier kcore.module.
Ajout d'une instruction jquery pour rendre cliquable le lien de premier niveau unique (cf. fichier pnf.js).

**2 - Modification pour Menu du Parc**
Liens "Recrutements" et "Marchés publics" retirés de la feature kcore.

*A noter !* *Pour chaque site, il faudra :*
- *créer un lien de premier niveau au nom du parc (ex. Le Parc national des Cévennes) pointant sur une page simple,*
- *ajouter tous les futurs liens de ce menu en tant que fils du lien précédent.*

**3 - Modifications pour Menu Les Parcs nationaux en France**
Ajout d'un lien de premier niveau pointant sur une page simple. Elle doit être présente sur tous les sites et afficher le même contenu.
Export de ce node page simple et du lien de menu correspondant.

**4 - Modifications pour le bloc de bas de page**
Ce bloc est un clone du menu du Parc.
Problème : sur la maquette, il n'affiche que les liens de second niveau, le lien de premier niveau, lui, a disparu.
Solution : code custom dans le hook kcore_block_view() du fichier kcore.module. Ce code intercepte le contenu du menu, supprime le lien de premier niveau, récupère les liens de niveau 2 et  les remonte au premier niveau. Un peu poilu, le code, mais ça fonctionne très bien.
