### ISSUE TITLE
Paragraph - bundle

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#63]
La mise en place des bundles Paragraph est notre priorité !
(nous verrons plus tard si il est possible d'intégrer le dernier bundle maquetté)

**Comment by jabberwooki** [comment]
Liste des bundles (Paragraph types) à créer d'après la maquette de Cécile :
- Slideshow pleine largeur
- Texte orangé et en italique
- h2, h3, h4 ... ? (comprends pas bien la demande)
- Phrase en majuscule (3 couleurs bleu, vert, marron)
- Paragraphe sur fond gris
- Produit achetable en boutique
- Liste de documents utiles
- Citation avec guillemets
- 3 image en ligne
- Texte à gauche, image à droite 50/50
- Texte 2 colonnes 50/50
- Vidéo pleine largeur
- Paragraphes accordéon 2 colonnes 50/50
- Carte pleine largeur
- 3 images en ligne avec apparition du picto **+** au survol et ouverture d'un slideshow en overlay au clic, comme sur [The Bookseller](http://www.thebookseller.com/bookseller-industry-awards/2015/judges). Celui-là, il fait par rire !
