### ISSUE TITLE
Bloc langue / titre à supprimer

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#7]
Le titre du bloc ne doit pas être affiché.

**Comment by jabberwooki** [comment]
Etonnant. Le paramétrage titre=<none> est bien exporté pour le bloc langue.
C'est visible sur github dans ce fichier :
https://github.com/jabberwooki/pnf/blob/develop/repository/modules/features/kcore/kcore.features.fe_block_settings.inc
à la ligne 98.

Un vidage de cache peut-être ?
