### ISSUE TITLE
Bloc langue / langue active bug

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#8]
La langue active devrait être affichée. On voit quelle est la langue active uniquement en déroulant la liste... Faut-il télécharger une librairie js pour avoir un résultat conforme ?

**Comment by sographik** [comment]
Voir le css commenter pour tester les padding du select

**Comment by jabberwooki** [comment]
La langue active est visible en fait. C'est l'affichage bootstrap du select qui empêche de la voir.
Ceci dit, le module lang_dropdown permet d'utiliser 3 librairies javascript différentes pour générer un code différent du select de base.
A voir si le pb n'est pas résolu simplement en css.
