### ISSUE TITLE
Bloc Agenda accueil modifs à faire

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#9]
Il ne doit pas y avoir de résumé, et il faut regarder la maquette : date - titre- catégorie - lieu

**Comment by zakxxi** [comment]
Pour information j'ai du activer les modules ds_extra (ajouté à feat kcore) et ds_bootstrap_layouts (ajouté à kbootstrap). Faut-il aussi les ajouter dans le profil d'install ?
