### ISSUE TITLE
Paragraph Texte et Image 50/50

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#96]
Texte-image (50/50) : Lightbox image bug légende = caption-value
Image-texte (50/50) : L'image ne s'adapte pas correctement en petit format (pas proportionnel) - Lightbox image bug légende = caption-value exemple : (les-activites-de-pleine-nature)

**Comment by jabberwooki** [comment]
- Dans la gestion de l'affichage des 2 modèles Texte-image (50/50) et Image-texte (50/50), Colorbox est paramétré pour utiliser la valeur de ALT comme légende d'image et, via un hook_entity_view(), on copie le contenu du champ Légende dans ALT.
- Création d'un style d'image "Largeur 360" (pas de hauteur définie). Ainsi, les images au format portrait ne sont plus tronquées.
- Le champ Image est passé de unique à multiple.

**Comment by webmanagerPNF** [comment]
Super ! Mais est-il possible de modifier la CSS pour que la légende apparaisse en plus petit comme sur les maquettes SVP...Merci d'avance.

**Comment by sographik** [comment]
un exemple de page sur lequel on a ce cas ?

**Comment by webmanagerPNF** [comment]
Accueil > Des découvertes > La destination Parc national des Cévennes > Infos utiles

**Comment by sographik** [comment]
c'est fait, il faut regarder la preprod
