### ISSUE TITLE
Paragraph SCALD

### ISSUE THREAD

**Issue by sographik** [jabberwooki/pnf#97]
Paragraph : Texte : CkEditor : L'option d'ajout d'image dans le texte ne fonctionne pas. Le bouton Explorer le serveur ne fonctionne pas. Voir pour supprimer cette fonction puisque cela fonctionne par glisser déposer depuis SCALD.
Lorsque l'on glisse et dépose une image de SCLAD cela affiche le nom de l'image dans le texte et cela affiche le nom de l'image en ALT. Après modification du texte alternatif dans les propriétés de l'image cela ne change pas le TITLE... (voir le parc sur les réseaux sociaux)
La fonction de lightbox n'est pas disponible dans ce cas ?

**Comment by jabberwooki** [comment]
Un glisser/déposer depuis Scald affiche maintenant l'image au lieu de son nom.
Par défaut, Scald utilise le titre de l'atome comme texte alternatif. Pour changer ce texte, il faut modifier le titre de l'atome.

La fonction de lightbox n'est pas disponible. Cela ne fait pas partie de la demande initiale.
